version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: serfile
    ports:
      - "8080:8080"
    volumes:
      - /path/to/serve:/app/app/static/root
    restart: unless-stopped
